// writes the MUTE brand-kit scenes into _studio/src (then: node _studio/render.js)
const fs = require('fs'), path = require('path'); const S = path.join(__dirname, 'src');
const mark = (w) => `<svg viewBox="0 0 40 40" style="width:${w}px"><defs><linearGradient id="lg" x1="0" x2="1"><stop offset="0" stop-color="#00c805"/><stop offset="1" stop-color="#7dff8a"/></linearGradient></defs><path d="M6 15h7l8-7v24l-8-7H6z" fill="#ecf6ee"/><path d="M27 14l8 12M35 14l-8 12" stroke="url(#lg)" stroke-width="3.6" stroke-linecap="round"/></svg>`;
const page = (body, css = '') => `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2400px;height:1350px}.pad{position:absolute;inset:110px 130px}.kick{font-family:Michroma;font-size:22px;letter-spacing:.3em;color:#6f8577;text-transform:uppercase}.foot{position:absolute;left:130px;right:130px;bottom:80px;display:flex;justify-content:space-between;align-items:center;font-size:26px;letter-spacing:.18em;color:#a9bcae}.foot b{font-family:Michroma;font-weight:400;letter-spacing:.34em;color:#ecf6ee;display:flex;align-items:center;gap:22px}h1{font-family:Michroma;font-weight:400;text-transform:uppercase;line-height:1.14}.cut{clip-path:polygon(28px 0,100% 0,100% calc(100% - 28px),calc(100% - 28px) 100%,0 100%,0 28px)}.glass{display:inline-block;background:linear-gradient(100deg,#00c805,#19d81f,#7dff8a);filter:blur(14px);border-radius:10px}${css}</style><body><div class="amb"></div><div class="scan"></div>${body}<div class="foot"><b>${mark(54)}MUTE</b><span>mutemoneyrh.xyz · @MuteMoneyRH · Robinhood Chain</span></div>`;
fs.writeFileSync(path.join(S, 'mute-pfp.html'), `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2000px;height:2000px;display:grid;place-items:center}</style><body><div class="amb" style="opacity:.55"></div>${mark(1100)}`);
fs.writeFileSync(path.join(S, 'mute-banner.html'), `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:3000px;height:1000px}h1{position:absolute;left:190px;top:250px;font-family:Michroma;font-weight:400;font-size:150px;line-height:1.15;text-transform:uppercase}p{position:absolute;left:198px;bottom:150px;font-family:Sora;font-weight:300;font-size:44px;letter-spacing:.08em;color:#a9bcae}.m{position:absolute;right:300px;top:240px}</style><body><div class="amb"></div><h1>Dollars with<br>the <span class="iri">sound off.</span></h1><p>MUTE · mUSD · private dollars on Robinhood Chain · mutemoneyrh.xyz</p><div class="m">${mark(520)}</div>`);
fs.writeFileSync(path.join(S, 'mute-keyart.html'), page(`<div class="pad"><div class="kick">private dollars · Robinhood Chain</div><h1 style="font-size:128px;margin-top:70px">Dollars with<br>the <span class="iri">sound off.</span></h1><p style="font-size:42px;color:#a9bcae;max-width:1250px;margin-top:60px;line-height:1.6">Mint a dollar against USDG. Mute it. The <b style="color:#ecf6ee;font-weight:500">amount and both parties never reach the ledger.</b></p></div><div style="position:absolute;right:170px;top:560px">${mark(440)}</div>`));
const steps = [['01', 'Mint', 'Deposit USDG on Robinhood Chain. Most becomes hard collateral. The algorithmic share buys $MUTE at market and erases it.'], ['02', 'Mute', 'Your mUSD becomes a note encrypted only to you. To everyone else the balance is unreadable.'], ['03', 'Send', 'Amount, sender and recipient stay hidden. The ledger holds one nullifier and one commitment.']];
fs.writeFileSync(path.join(S, 'mute-howitworks.html'), page(`<div class="pad"><div class="kick">how it works</div><h1 style="font-size:96px;margin-top:40px">Three moves. <span class="iri">No names.</span></h1><div class="g">${steps.map((s) => `<div class="s cut"><div class="n">${s[0]}</div><h2>${s[1]}</h2><p>${s[2]}</p></div>`).join('')}</div></div>`, `.g{display:grid;grid-template-columns:repeat(3,1fr);gap:36px;margin-top:80px}.s{background:#0a0f0cdd;padding:56px 50px;height:560px;box-shadow:inset 0 0 0 1px #25382b}.n{font-family:Michroma;font-size:30px;color:#00c805}.s h2{font-family:Michroma;font-weight:400;font-size:64px;text-transform:uppercase;margin:36px 0 30px}.s p{font-size:32px;line-height:1.6;color:#a9bcae}`));
const feats = [['Drop', 'Send muted dollars as a link. No address needed.'], ['Mirror', 'A read-only view key. Show one person, nobody else.'], ['Blind Desk', 'Long or short tokenized stocks. Ticker, size and P&L stay muted.'], ['Bonds · Cryo', '$MUTE at −20%, or lock 48h at −30% and earn 80% APY.'], ['Silent Yield', '40% of every fee streams to muted holders. No staking, no lock.'], ['Erase', 'Every fee buys $MUTE at market and removes it from supply.'], ['Relays', 'Bring a wallet in, earn 20% of every fee it pays. Forever.'], ['Real USDG', 'Deposits verified on-chain. Withdrawals paid from a cold wallet.']];
fs.writeFileSync(path.join(S, 'mute-features.html'), page(`<div class="pad"><div class="kick">the console</div><h1 style="font-size:84px;margin-top:36px">Everything private money <span class="iri">needs.</span></h1><div class="g">${feats.map((f, i) => `<div class="f"><i>0${i + 1}</i><h2>${f[0]}</h2><p>${f[1]}</p></div>`).join('')}</div></div>`, `.g{display:grid;grid-template-columns:repeat(4,1fr);gap:0 50px;margin-top:64px}.f{border-top:1px solid #25382b;padding:34px 0 46px;height:330px}.f i{font-family:Michroma;font-style:normal;font-size:20px;color:#6f8577}.f h2{font-weight:500;font-size:44px;margin:16px 0 14px}.f p{font-size:27px;line-height:1.55;color:#a9bcae}`));
fs.writeFileSync(path.join(S, 'mute-ledger.html'), page(`<div class="pad"><div class="kick">what the ledger sees</div><h1 style="font-size:96px;margin-top:40px">Same dollar. <span class="iri">No sound.</span></h1><div class="r cut"><div class="l">A public stablecoin transfer</div><div class="d"><span>0x71c2…9e4a → 0xb03f…11d7</span><span>$48,200.00</span></div><div class="w">Everyone can read who paid whom, and how much. Forever.</div></div><div class="r cut"><div class="l">A muted mUSD transfer</div><div class="d"><span>nullifier 9f2c…  +  commitment 4ab1…</span><em class="glass" style="width:420px;height:64px"></em></div><div class="w">No amount. No sender. No recipient.</div></div></div>`, `.r{background:#0a0f0cdd;box-shadow:inset 0 0 0 1px #25382b;padding:46px 56px;margin-top:50px}.l{font-family:Michroma;font-size:24px;letter-spacing:.2em;text-transform:uppercase;color:#6f8577}.d{display:flex;justify-content:space-between;align-items:center;font-size:56px;font-weight:400;margin:26px 0 18px}.w{font-size:32px;color:#a9bcae}`));
let r = fs.readFileSync(path.join(__dirname, 'render.js'), 'utf8');
r = r.replace(/const SIZES = \{[\s\S]*?\};/, "const SIZES = {\n  'mute-pfp': [2000, 2000],\n  'mute-banner': [3000, 1000],\n  'mute-keyart': [2400, 1350],\n  'mute-howitworks': [2400, 1350],\n  'mute-features': [2400, 1350],\n  'mute-ledger': [2400, 1350],\n};").replace(/hushchrome_/g, 'mutechrome_'); fs.writeFileSync(path.join(__dirname, 'render.js'), r);
console.log('mute kit scenes written');
